default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: secret_friend_development

test:
  <<: *default
  database: secret_friend_test

production:
  <<: *default
  database: secret_friend_production
  username: secret_friend
  password: <%= ENV['SECRET_FRIEND_DATABASE_PASSWORD'] %>
